name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # This schedule runs the workflow daily at midnight

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email eng21ct0007@dsu.edu.in
        git config --global user.name hrk-2109

    - name: Sync with my-app-dev
      run: |
        git remote add upstream https://github.com/Techtidy/my-app-dev.git
        git fetch upstream
        git checkout main # Replace with the branch you want to sync
        git merge upstream/main --no-edit  # Replace with the branch you want to sync
        git push origin main  # Replace with the branch you want to sync
